new updates to pii.sh
infinite-omicron/pii-redactor pull request #7
Opened 2021-09-29 19:23 UTC by Ada-Codina

testing the Pull Request feature and adding new code to PII

2021-09-29 19:25 UTC, oxr463 requested changes

2021-09-29 19:25 UTC, oxr463 commented on pii_redactor.sh
> +#varibles in use
```suggestion
# variables in use
```

2021-09-29 19:33 UTC, oxr463 approved these changes

2021-09-29 19:34 UTC, oxr463 commented
Since this is still WIP, I'm going to convert it to a draft.

2021-09-30 18:18 UTC, oxr463 commented on pii_redactor.sh
> +    echo "PII_Redaction.sh version is ${version}"
```suggestion
    echo "pii-redactor version ${version}"
```

2021-10-04 19:16 UTC, Ada-Codina reviewed
adding changes to main res

2021-10-04 20:31 UTC, Ada-Codina reviewed
upgrade

2021-10-04 21:04 UTC, oxr463 commented on pii_redactor.sh
> +version="0.0.4"
I wouldn't increment the version number until we actually release the first version.
```suggestion
version="0.0.1"
```

2021-10-13 20:03 UTC, oxr463 commented
1. No arguments.

```
./pii_redactor.sh 
./pii_redactor.sh: line 9: $1: unbound variable
```

2. Current directory:

```
./pii_redactor.sh .
Success
```

3. Help flag:

```
./pii_redactor.sh -h
USAGE: 
pii_redactor [command] || <directory that holds cluster.yml>

GLOBAL COMMANDS:
  -h, --help            Show this message
  -d, --debug           Output debug messages
  -v, --verbose         verbose mode
  -ver, --version       Print version
```

2021-11-17 01:03 UTC, oxr463 commented on .github/workflows/checker.yml
> +name: Shellchecker
```suggestion
name: shellcheck
```

2021-11-17 01:04 UTC, merged